root_domain: kindmanage.dev
encryption_key: a8fe06b251001f09ce04861fe9a8142a9
emails:
  password_change:
    from: no-reply@<host>
    subject: Password Change
  registration:
    from: no-reply@<host>
    subject: Registration